apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 172000040203.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 172000040203.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 1dd5ef67
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
